"""
Runtime telemetry event model for the PerfLens project.

Purpose:
    Represents a single telemetry event generated by the
    simulation engine.

Responsibilities:
    - Store generated telemetry.
    - Validate event state.
    - Support serialization.

This model does NOT:
    - Generate telemetry.
    - Publish events.
    - Persist data.
"""

# ============================================================================
# Standard Library Imports
# ============================================================================

from __future__ import annotations

from dataclasses import asdict
from dataclasses import dataclass
from dataclasses import field
from datetime import UTC
from datetime import datetime
from typing import Any
from uuid import uuid4

# ============================================================================
# Local Imports
# ============================================================================

from src.config.exceptions import ConfigurationValidationError


# ============================================================================
# Classes
# ============================================================================


@dataclass(slots=True)
class TelemetryEvent:
    """
    Runtime telemetry event.
    """

    event_id: str = field(
        default_factory=lambda: str(uuid4())
    )

    timestamp: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )

    service_id: str = ""

    scenario_id: str = ""

    metrics: dict[str, float] = field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        """
        Validate the telemetry event.
        """
        self._validate_identity()

    # =======================================================================
    # Validation
    # =======================================================================

    def _validate_identity(self) -> None:
        """
        Validate event identity.
        """
        if not self.service_id.strip():
            raise ConfigurationValidationError(
                message="Service identifier cannot be empty.",
            )

        if not self.scenario_id.strip():
            raise ConfigurationValidationError(
                message="Scenario identifier cannot be empty.",
            )

    # =======================================================================
    # Metric Operations
    # =======================================================================

    def add_metric(
        self,
        metric_id: str,
        value: float,
    ) -> None:
        """
        Add or update a metric value.

        Args:
            metric_id:
                Metric identifier.

            value:
                Generated metric value.
        """
        if not metric_id.strip():
            raise ConfigurationValidationError(
                message="Metric identifier cannot be empty.",
            )

        self.metrics[metric_id] = value

    def metric(
        self,
        metric_id: str,
    ) -> float:
        """
        Return a metric value.

        Args:
            metric_id:
                Metric identifier.

        Returns:
            Generated metric value.

        Raises:
            KeyError:
                If the metric does not exist.
        """
        return self.metrics[metric_id]

    def has_metric(
        self,
        metric_id: str,
    ) -> bool:
        """
        Determine whether a metric exists.
        """
        return metric_id in self.metrics

    @property
    def metric_count(self) -> int:
        """
        Return the number of generated metrics.
        """
        return len(self.metrics)

    # =======================================================================
    # Serialization
    # =======================================================================

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the telemetry event to a dictionary.

        Returns:
            Dictionary representation suitable for JSON
            serialization.
        """
        data = asdict(self)

        data["timestamp"] = self.timestamp.isoformat()

        return data