receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  kafka:
    brokers:
      - "${EVENTHUB_NAMESPACE}.servicebus.windows.net:9093"
    # Change this from 2.8.0 to 2.0.0 to fix the request key metadata version mismatch
    protocol_version: 2.0.0
    client_id: perflens-collector
    auth:
      sasl:
        mechanism: PLAIN
        username: "$ConnectionString"
        password: "${EVENTHUB_CONNECTION_STRING}"
    tls:
      insecure: false
    metrics:
      topic: "${EVENTHUB_NAME}"
      encoding: otlp_proto
      
service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - kafka