receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

  kafka:
    brokers:
      - kafka:9094
    protocol_version: 2.8.0
    # Nesting the parameters inside the metrics signal block
    metrics:
      topic: perflens.metrics
      encoding: otlp_proto

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - kafka